services:
  - type: web 
    name: bionic
    env: node  
    buildCommand: npm install && npm run build  
    startCommand: npm start  
    routes:
      - source: /*
        destination: /index.html